In [2]:
import pandas as pd
from matplotlib import pyplot as plt
import plotly.graph_objects as go # or plotly.express as px
from plotly.subplots import make_subplots
import numpy as np
from urllib.request import urlopen
import json

In [3]:
H1b = pd.read_csv("Employer Information.csv", encoding = "utf=16", sep = "\t")
H1b.head()

C:\Users\anana\AppData\Local\Temp\ipykernel_44532\3666231126.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  H1b = pd.read_csv("Employer Information.csv", encoding = "utf=16", sep = "\t")

,Line by line,Fiscal Year,Employer (Petitioner) Name,Tax ID,Industry (NAICS) Code,Petitioner City,Petitioner State,Petitioner Zip Code,New Employment Approval,New Employment Denial,Continuation Approval,Continuation Denial,Change with Same Employer Approval,Change with Same Employer Denial,New Concurrent Approval,New Concurrent Denial,Change of Employer Approval,Change of Employer Denial,Amended Approval,Amended Denial
0,1,2023,NaN,NaN,NaN,FAIRFIELD,IA,52556.0,0,1,0,0,0,0,0,0,0,0,0,0
1,2,2023,NaN,8070.0,51 - Information,WILMINGTON,DE,19801.0,1,0,0,0,0,0,0,0,0,0,0,0
2,3,2023,NaN,8424.0,"54 - Professional, Scientific, and Technical S...",BROOKLYN,NY,11220.0,0,0,1,0,0,0,0,0,0,0,0,0
3,4,2023,NaN,8435.0,52 - Finance and Insurance,NEW YORK,NY,10017.0,0,0,1,0,0,0,0,0,0,0,0,0
4,5,2023,1 800 CONTACTS INC,1643.0,42 - Wholesale Trade,DRAPER,UT,84020.0,0,0,0,0,0,0,0,0,2,0,0,0

In [4]:
H1b_2 = pd.read_csv("Employer Information 2.csv", encoding = "utf-16", sep="\t")
H1b_2.tail()

C:\Users\anana\AppData\Local\Temp\ipykernel_44532\843306738.py:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  H1b_2 = pd.read_csv("Employer Information 2.csv", encoding = "utf-16", sep="\t")

,Line by line,Fiscal Year,Employer (Petitioner) Name,Tax ID,Industry (NAICS) Code,Petitioner City,Petitioner State,Petitioner Zip Code,New Employment Approval,New Employment Denial,Continuation Approval,Continuation Denial,Change with Same Employer Approval,Change with Same Employer Denial,New Concurrent Approval,New Concurrent Denial,Change of Employer Approval,Change of Employer Denial,Amended Approval,Amended Denial
148505,"148,506",2024,ZYNO MEDICAL LLC,7390.0,31-33 - Manufacturing,NATICK,MA,1760.0,0,0,0,0,0,0,0,0,0,0,2,0
148506,"148,507",2024,ZYON DIGITAL SOLUTIONS LLC,3124.0,"54 - Professional, Scientific, and Technical S...",EL PASO,TX,79911.0,1,0,0,0,0,0,0,0,2,0,0,0
148507,"148,508",2024,ZYSCOVICH LLC,4852.0,"54 - Professional, Scientific, and Technical S...",MIAMI,FL,33132.0,1,0,0,0,0,0,0,0,0,0,0,0
148508,"148,509",2024,ZYTUS INC,96.0,"54 - Professional, Scientific, and Technical S...",RICHMOND,VA,23238.0,2,0,0,0,0,0,0,0,0,0,0,0
148509,"148,510",2024,ZYWIE INC,9321.0,"54 - Professional, Scientific, and Technical S...",JOHNS CREEK,GA,30097.0,0,0,1,0,0,0,0,0,0,0,0,0

For this milestone, I changed the order of the files to merge so that the sort can be easier.

In [5]:
H1b_comp = pd.concat([H1b_2, H1b], ignore_index= True)
H1b_comp.head()

,Line by line,Fiscal Year,Employer (Petitioner) Name,Tax ID,Industry (NAICS) Code,Petitioner City,Petitioner State,Petitioner Zip Code,New Employment Approval,New Employment Denial,Continuation Approval,Continuation Denial,Change with Same Employer Approval,Change with Same Employer Denial,New Concurrent Approval,New Concurrent Denial,Change of Employer Approval,Change of Employer Denial,Amended Approval,Amended Denial
0,1,2026,NaN,4902.0,31-33 - Manufacturing,RANDOLPH,MA,2368.0,0,0,1,0,0,0,0,0,0,0,0,0
1,2,2026,NaN,9012.0,31-33 - Manufacturing,HILLSBOROUGH,NH,3244.0,0,0,1,0,0,0,0,0,0,0,0,0
2,3,2026,1 EMC LLC,9142.0,72 - Accommodation and Food Services,FINDLAY,OH,45840.0,1,0,0,0,0,0,0,0,0,0,0,0
3,4,2026,1 NET SOFTWARE TECHNOLOGIES,9485.0,"54 - Professional, Scientific, and Technical S...",IRVING,TX,75063.0,0,0,0,0,0,0,0,0,0,0,1,0
4,5,2026,1-800-FLOWERS COM INC,7311.0,44-45 - Retail Trade,JERICHO,NY,11753.0,0,0,1,0,0,0,0,0,0,0,0,0

In [6]:
H1b_comp.tail()

,Line by line,Fiscal Year,Employer (Petitioner) Name,Tax ID,Industry (NAICS) Code,Petitioner City,Petitioner State,Petitioner Zip Code,New Employment Approval,New Employment Denial,Continuation Approval,Continuation Denial,Change with Same Employer Approval,Change with Same Employer Denial,New Concurrent Approval,New Concurrent Denial,Change of Employer Approval,Change of Employer Denial,Amended Approval,Amended Denial
321790,"173,281",2021,ZYTUS INC,96.0,"54 - Professional, Scientific, and Technical S...",HENRICO,VA,23238.0,0,0,0,0,2,0,0,0,1,0,0,0
321791,"173,282",2021,ZYTUS INC,96.0,"54 - Professional, Scientific, and Technical S...",RICHMOND,VA,23238.0,1,0,0,0,0,0,0,0,0,0,0,0
321792,"173,283",2021,ZYWAVE INC,743.0,"54 - Professional, Scientific, and Technical S...",MILWAUKEE,WI,53226.0,1,0,0,0,0,0,0,0,0,0,1,0
321793,"173,284",2021,ZYWIE INC,9321.0,"54 - Professional, Scientific, and Technical S...",DULUTH,GA,30097.0,0,0,1,0,0,0,0,0,0,0,0,0
321794,"173,285",2021,ZZAN HILLCREST INC,5526.0,72 - Accommodation and Food Services,SAN DIEGO,CA,92103.0,0,0,0,0,0,0,0,0,1,0,0,0

In [7]:
H1b_comp = H1b_comp.drop(columns=["Line by line"])

In [8]:
H1b_comp.shape

(321795, 19)

In [9]:
H1b_comp.columns = H1b_comp.columns.str.strip()

In [10]:
H1b_comp["Fiscal Year"].value_counts()

Fiscal Year
2025    62324
2024    61824
2022    59631
2023    57394
2021    56260
2026    24362
Name: count, dtype: int64

In [11]:
H1b_comp["Petitioner State"].unique()

array(['MA', 'NH', 'OH', 'TX', 'NY', 'TN', 'CA', 'CO', 'VA', 'IL', 'AL',
       'CT', 'NC', 'NJ', 'NM', 'SC', 'MN', 'MI', 'FL', 'MD', 'GA', 'NV',
       'WA', 'MO', 'KY', 'UT', 'OK', 'PA', 'WI', 'LA', 'HI', 'AZ', 'IN',
       'DE', 'AR', 'DC', 'WV', 'KS', 'ID', 'OR', 'NE', 'AK', 'WY', 'RI',
       'IA', 'GU', 'ND', 'SD', 'MS', 'ME', nan, 'MT', 'VT', 'PR', 'MP',
       'AA', 'VI', 'XX', 'AS', 'MH', 'AP'], dtype=object)

In [12]:
State_map = {"AL" : "Alabama",
"AK" : "Alaska",
"AZ" : "Arizona",
"AR" : "Arkansas",
"CA" : "California",
"CO" : "Colorado",
"CT" : "Connecticut",
"DE" : "Delaware",
"DC" : "District of Columbia",
"FL" : "Florida",
"GA" : "Georgia",
"HI" : "Hawaii",
"ID" : "Idaho",
"IL" : "Illinois",
"IN" : "Indiana",
"IA" : "Iowa",
"KS" : "Kansas",
"KY" : "Kentucky",
"LA" : "Louisiana",
"ME" : "Maine",
"MD" : "Maryland",
"MA" : "Massachusetts",
"MI" : "Michigan",
"MN" : "Minnesota",
"MS" : "Mississippi",
"MO" : "Missouri",
"MT" : "Montana",
"NE" : "Nebraska",
"NV" : "Nevada",
"NH" : "New Hampshire",
"NJ" : "New Jersey",
"NM" : "New Mexico",
"NY" : "New York",
"NC" : "North Carolina",
"ND" : "North Dakota",
"OH" : "Ohio",
"OK" : "Oklahoma",
"OR" : "Oregon",
"PA" : "Pennsylvania",
"RI" : "Rhode Island",
"SC" : "South Carolina",
"SD" : "South Dakota",
"TN" : "Tennessee",
"TX" : "Texas",
"UT" : "Utah",
"VT" : "Vermont",
"VA" : "Virginia",
"WA" : "Washington",
"WV" : "West Virginia",
"WI" : "Wisconsin",
"WY" : "Wyoming" }

In [13]:
H1b_comp["Petitioner_State_c"] = H1b_comp["Petitioner State"].astype("category")
H1b_comp['Petitioner_State_c'] = H1b_comp['Petitioner_State_c'].cat.rename_categories(State_map)

In [14]:

#with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
#    counties = json.load(response)

#import pandas as pd
#df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/fips-unemp-16.csv",
#                   dtype={"fips": str})

#import plotly.express as px

#fig = px.choropleth(df, geojson=counties, locations='fips', color='unemp',
                           #color_continuous_scale="Viridis",
                           #range_color=(0, 12),
                           #scope="usa",
                           #labels={'unemp':'unemployment rate'}
#)
#fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
#fig.show()

In [15]:
fig = go.Figure(go.Scattergeo())
fig.update_geos(
    visible = False, resolution = 110, scope = "usa",
    showcountries = True, countrycolor = "Black",
    showsubunits = True, 
    subunitcolor = "Black"
)
fig.update_layout(height = 500, margin={"r": 0, "t" : 50, "l" : 10, "b" : 50})
fig.show()
# source - https://plotly.com/python/map-configuration/

go.Scatter can be used to make the map and plot the scatter points through layers on it. But for my data, I want to just build a choropleth map which can be directly made through Plotly graph objects

In [16]:
state_counts = H1b_comp.groupby("Petitioner State").count()['Employer (Petitioner) Name']
#state_counts_top10 = state_counts.nlargest(10)

fig2 = go.Figure(go.Choropleth(
    locations = state_counts.index,
    z = state_counts.values,
    text=state_counts.index.map(State_map),
    locationmode = "USA-states",
    colorscale = "Blues",
    colorbar_title = "H1B Petitions",
    hovertemplate="<b>%{text}</b><br>Petitions: %{z:,}<extra></extra>"
))

fig2.update_geos(
    visible = False, resolution = 110, scope = "usa",
    showcountries = True, countrycolor = "Black",
    showsubunits = True, 
    subunitcolor = "Black"
)

fig2.update_layout(
    title = "H1B Petitions by State (2021-2025)",
    height = 500,
    margin = {"r": 0, "t" : 50, "l" : 10, "b" : 50}
)

fig2.show()

# Source - https://claude.ai/chat/50981cae-65c2-43af-84f6-fcadafb66e60

Now I am trying to only show the Top 10 states by the number of unique employers

In [17]:
state_counts = H1b_comp.groupby("Petitioner State").count()['Employer (Petitioner) Name']
state_counts_top10 = state_counts.nlargest(10)

fig3 = go.Figure(go.Choropleth(
    locations = state_counts_top10.index,
    z = state_counts_top10.values,
    text=state_counts_top10.index.map(State_map),
    locationmode = "USA-states",
    colorscale = "Blues",
    colorbar_title = "H1B Petitions",
    hovertemplate="<b>%{text}</b><br>Petitions: %{z:,}<extra></extra>"
))

fig3.update_geos(
    visible = False, resolution = 110, scope = "usa",
    showcountries = True, countrycolor = "Black",
    showsubunits = True, 
    subunitcolor = "Black"
)

fig3.update_layout(
    title = "H1B Petitions by State (2021-2025)",
    height = 500,
    margin = {"r": 0, "t" : 50, "l" : 10, "b" : 50}
)

fig3.show()

pandas.DataFrame.replace

Now that I have my Top 10 states, I would like to see the pie chart again

In [18]:
fig4 = go.Figure(
    data=[
    go.Pie(
        labels=state_counts_top10.index.map(State_map), 
        values=state_counts_top10.values,
        title="Petitioner States Percentage"
        )])

fig4.show()

In [19]:
year_state = H1b_comp.groupby(
    ["Fiscal Year", "Petitioner State"]
).count()["Employer (Petitioner) Name"].reset_index(name = "petitions")

year_state_top10 = year_state[year_state["Petitioner State"].isin(state_counts_top10)]

year_state_top10["State Name"] = year_state_top10["Petitioner State"].map(State_map)

fig5 = go.Figure()
for state in state_counts_top10.index.tolist():
    state_data = year_state_top10[year_state_top10["Petitioner State"] == state]
    fig5.add_trace(go.Scatter(
        x = state_data["Fiscal Year"],
        y = state_data["petitions"],
        mode = "lines+markers",
        name = State_map[state],
        hovertemplate="<b>" + State_map[state] + "</b><br>Year: %{x}<br>Petitions : %{y:, }<extra></extra>"        
    ))


fig5.update_layout(
    title = "H1B Petition Trends by Top 10 States (2021-2025)",
    xaxis_title = "Fiscal Year",
    yaxis_title = "H1B Petitions",
    height = 500,
    margin={"r": 20, "t": 50, "l": 10, "b": 50},
    xaxis=dict(dtick=1),                                 
    # shows every year on x axis
    legend_title="State"
)

fig5.show()

 I had to add .reset_index() to the groupby function because Petitioner State is stuck in Index and not acting as a regular column. Since we are using two variables to groupby, we'll use reset_index here so that Pandas treats both the variables as two distinct columns.

In [20]:
print(state_counts_top10)

Petitioner State
CA    59890
TX    34501
NY    34164
NJ    19898
IL    15219
MA    15006
FL    13584
GA    10996
VA    10983
MI    10505
Name: Employer (Petitioner) Name, dtype: int64

In [21]:
type(state_counts_top10)

pandas.core.series.Series

In [22]:
print(state_counts_top10)

Petitioner State
CA    59890
TX    34501
NY    34164
NJ    19898
IL    15219
MA    15006
FL    13584
GA    10996
VA    10983
MI    10505
Name: Employer (Petitioner) Name, dtype: int64

In [23]:
print(type(year_state))
print(year_state.head())

<class 'pandas.core.frame.DataFrame'>
   Fiscal Year Petitioner State  petitions
0         2021               AK         24
1         2021               AL        259
2         2021               AR        189
3         2021               AZ        665
4         2021               CA      10851

In [24]:
print(year_state_top10.shape)
print(year_state_top10.head())

(0, 4)
Empty DataFrame
Columns: [Fiscal Year, Petitioner State, petitions, State Name]
Index: []

In [25]:
print(year_state.columns)
print(year_state.head())

Index(['Fiscal Year', 'Petitioner State', 'petitions'], dtype='object')
   Fiscal Year Petitioner State  petitions
0         2021               AK         24
1         2021               AL        259
2         2021               AR        189
3         2021               AZ        665
4         2021               CA      10851

In [26]:
print(state_counts_top10.index.tolist())

['CA', 'TX', 'NY', 'NJ', 'IL', 'MA', 'FL', 'GA', 'VA', 'MI']

In [27]:
print(year_state[year_state["Petitioner State"].isin(['CA', 'TX', 'NY', 'NJ', 'IL', 'MA', 'FL', 'GA', 'VA', 'MI'])])

     Fiscal Year Petitioner State  petitions
4           2021               CA      10851
9           2021               FL       2216
10          2021               GA       1811
15          2021               IL       2685
20          2021               MA       2774
23          2021               MI       1940
33          2021               NJ       3552
36          2021               NY       6276
46          2021               TX       5495
48          2021               VA       1864
59          2022               CA      12039
64          2022               FL       2508
65          2022               GA       1842
70          2022               IL       2815
75          2022               MA       2931
78          2022               MI       1938
88          2022               NJ       3514
91          2022               NY       6381
101         2022               TX       5566
103         2022               VA       2035
116         2023               CA      10864
121         2023               FL       2319
122         2023               GA       1978
127         2023               IL       2650
132         2023               MA       2602
135         2023               MI       1914
145         2023               NJ       3587
148         2023               NY       6034
158         2023               TX       6223
160         2023               VA       1962
172         2024               CA      10835
177         2024               FL       2698
178         2024               GA       2340
183         2024               IL       2819
188         2024               MA       2756
192         2024               MI       1922
202         2024               NJ       3645
205         2024               NY       6270
215         2024               TX       7379
217         2024               VA       2111
231         2025               CA      11123
236         2025               FL       2880
237         2025               GA       2118
242         2025               IL       3008
247         2025               MA       2868
250         2025               MI       1980
260         2025               NJ       3824
263         2025               NY       6688
273         2025               TX       6856
275         2025               VA       2128
288         2026               CA       4178
293         2026               FL        963
294         2026               GA        907
299         2026               IL       1242
304         2026               MA       1075
307         2026               MI        811
317         2026               NJ       1776
320         2026               NY       2515
330         2026               TX       2982
332         2026               VA        883

Trying to find why the chart is still showing as empty. As figured out, the year_state_top10 turned out to be an empty DataFrame. This was because I was trying to pass state_counts_top10.index to it but that was a series and Pandas was trying to match its value but there was no match in Petitioner State. the isin() expects a list.

In [28]:
year_state = H1b_comp.groupby(
    ["Fiscal Year", "Petitioner State"]
).count()["Employer (Petitioner) Name"].reset_index(name = "petitions")

year_state_top10 = year_state[year_state["Petitioner State"].isin(state_counts_top10.index.tolist())]

year_state_top10["State Name"] = year_state_top10["Petitioner State"].map(State_map)

fig5 = go.Figure()
for state in state_counts_top10.index.tolist():
    state_data = year_state_top10[year_state_top10["Petitioner State"] == state]
    fig5.add_trace(go.Scatter(
        x = state_data["Fiscal Year"],
        y = state_data["petitions"],
        mode = "lines+markers",
        name = State_map[state],
        hovertemplate="<b>" + State_map[state] + "</b><br>Year: %{x}<br>Petitions : %{y:, }<extra></extra>"        
    ))


fig5.update_layout(
    title = "H1B Petition Trends by Top 10 States (2021-2025)",
    xaxis_title = "Fiscal Year",
    yaxis_title = "H1B Petitions",
    height = 500,
    margin={"r": 20, "t": 50, "l": 10, "b": 50},
    xaxis=dict(dtick=1),                                 
    # shows every year on x axis
    legend_title="State"
)

fig5.show()

#source - https://claude.ai/chat/50981cae-65c2-43af-84f6-fcadafb66e60

C:\Users\anana\AppData\Local\Temp\ipykernel_44532\1076136066.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [29]:
H1b_comp.columns

Index(['Fiscal Year', 'Employer (Petitioner) Name', 'Tax ID',
       'Industry (NAICS) Code', 'Petitioner City', 'Petitioner State',
       'Petitioner Zip Code', 'New Employment Approval',
       'New Employment Denial', 'Continuation Approval', 'Continuation Denial',
       'Change with Same Employer Approval',
       'Change with Same Employer Denial', 'New Concurrent Approval',
       'New Concurrent Denial', 'Change of Employer Approval',
       'Change of Employer Denial', 'Amended Approval', 'Amended Denial',
       'Petitioner_State_c'],
      dtype='object')

I started with groupby.count, however, I realise using the groupby.sum with the New Employment Approval would more accurately represent the data. Right now, all these figures just show the ncount of unique organizations per state.

Let me remake the choropleth map by just changing the .count to .sum and changing my grouping variable.

In [30]:
state_newvisa_app = H1b_comp.groupby("Petitioner State").sum()["New Employment Approval"]
state_newapprovals_top10 = state_counts.nlargest(10)

fig6 = go.Figure(go.Choropleth(
    locations = state_counts_top10.index,
    z = state_counts_top10.values,
    text=state_counts_top10.index.map(State_map),
    locationmode = "USA-states",
    colorscale = "Blues",
    colorbar_title = "H1B Petitions",
    hovertemplate="<b>%{text}</b><br>Petitions: %{z:,}<extra></extra>"
))

fig6.update_geos(
    visible = False, resolution = 110, scope = "usa",
    showcountries = True, countrycolor = "Black",
    showsubunits = True, 
    subunitcolor = "Black"
)

fig6.update_layout(
    title = "H1B Petitions by State (2021-2025)",
    height = 500,
    margin = {"r": 0, "t" : 50, "l" : 10, "b" : 50}
)

fig6.show()

TypeError: can only concatenate str (not "int") to str

In [32]:
type(H1b_comp["New Employment Approval"].iloc[0])

str

So this error occured because the variable New Employment Approval is stored as a string and not as a int, which is why the sum () is not able to work.

In [43]:
H1b_comp['NewEmpAppr_int'] = pd.to_numeric(H1b_comp['New Employment Approval'], errors='coerce')

In [46]:
type(H1b_comp["NewEmpAppr_int"])

pandas.core.series.Series

In [49]:
print(H1b_comp["NewEmpAppr_int"].dtype)
print(H1b_comp["NewEmpAppr_int"].tail(10))

float64
321785    0.0
321786    6.0
321787    2.0
321788    0.0
321789    1.0
321790    0.0
321791    1.0
321792    1.0
321793    0.0
321794    0.0
Name: NewEmpAppr_int, dtype: float64

In [51]:
H1b_comp.groupby("Petitioner State")["NewEmpAppr_int"].sum()

Petitioner State
AA         1.0
AK       485.0
AL      2008.0
AP         0.0
AR      4440.0
AS         0.0
AZ      9912.0
CA    102300.0
CO      5032.0
CT      5500.0
DC      3063.0
DE      2596.0
FL     18290.0
GA     18848.0
GU      1289.0
HI       412.0
IA      2554.0
ID      1334.0
IL     29804.0
IN      4441.0
KS      2472.0
KY      1827.0
LA      2189.0
MA     27015.0
MD     11582.0
ME       686.0
MH         1.0
MI     18067.0
MN      6666.0
MO      6108.0
MP       131.0
MS       949.0
MT       405.0
NC     14164.0
ND       790.0
NE      2392.0
NH      1151.0
NJ     54202.0
NM      1829.0
NV      1309.0
NY     53864.0
OH     10720.0
OK      1840.0
OR      2245.0
PA     19656.0
PR       142.0
RI      1816.0
SC      3586.0
SD      1248.0
TN      7061.0
TX     69249.0
UT      2841.0
VA     24363.0
VI        55.0
VT       364.0
WA     12183.0
WI      4177.0
WV       584.0
WY       488.0
XX         4.0
Name: NewEmpAppr_int, dtype: float64

In [52]:

state_newvisa_app = H1b_comp.groupby("Petitioner State")["NewEmpAppr_int"].sum()
state_newapprovals_top10 = state_newvisa_app.nlargest(10)

fig6 = go.Figure(go.Choropleth(
    locations = state_newapprovals_top10.index,
    z = state_newapprovals_top10.values,
    text=state_newapprovals_top10.index.map(State_map),
    locationmode = "USA-states",
    colorscale = "Greens",
    colorbar_title = "H1B Petitions",
    hovertemplate="<b>%{text}</b><br>Petitions: %{z:,}<extra></extra>"
))

fig6.update_geos(
    visible = False, resolution = 110, scope = "usa",
    showcountries = True, countrycolor = "Black",
    showsubunits = True, 
    subunitcolor = "Black"
)

fig6.update_layout(
    title = "H1B Petitions by State (2021-2025)",
    height = 500,
    margin = {"r": 0, "t" : 50, "l" : 10, "b" : 50}
)

fig6.show()

So the error was because I was trying to .sum()["NewEmpAppr_int"], rather than ["NewEmpAppr_int"].sum(). Because of this, it summed all the columns first and then was trying to select the new variable which was giving me the concatenation error. However, I had to select the column first and then sum it

Now as I can see, California still has the lasrgest number of New petitions approved

In [ ]:
print(H1b_comp[H1b_comp["Petitioner State"] == "CA"].groupby("Industry (NAICS) Code")["NewEmpAppr_int"].sum().nlargest(10))

#Source - https://claude.ai/chat/50981cae-65c2-43af-84f6-fcadafb66e60

Industry (NAICS) Code
54 - Professional, Scientific, and Technical Services                            43338.0
31-33 - Manufacturing                                                            21044.0
51 - Information                                                                 12848.0
61 - Educational Services                                                         8024.0
52 - Finance and Insurance                                                        4636.0
62 - Health Care and Social Assistance                                            2484.0
44-45 - Retail Trade                                                              1892.0
42 - Wholesale Trade                                                              1290.0
23 - Construction                                                                  800.0
56 - Administrative and Support and Waste Management and Remediation Services      743.0
Name: NewEmpAppr_int, dtype: float64

In [57]:
ca_industry = H1b_comp[H1b_comp["Petitioner State"] == "CA"].groupby("Industry (NAICS) Code")["NewEmpAppr_int"].sum().nlargest(10).sort_values()

fig7 = go.Figure(go.Bar(
    x=ca_industry.values,
    y=ca_industry.index,
    orientation="h",
    marker=dict(
        color=ca_industry.values,
        colorscale="Greens",
        showscale=False
    ),
    hovertemplate="<b>%{y}</b><br>Approvals: %{x:,}<extra></extra>"
))

fig7.update_layout(
    title="Top 10 Industries by H1B Approvals in California (2021-2026)",
    xaxis_title="New Employment Approvals",
    yaxis_title="Industry",
    height=500,
    margin={"r": 20, "t": 50, "l": 10, "b": 50}
)

fig7.show()

So now I know California still dominates based on the New Employment Approvals total and the industry that has the highest approvals is the Professional, Scientific and Technical Services, which makes sense as California is home to the Silicon Valley and a vast majority of major Tech companies are headquartered there

In [56]:
print(H1b_comp[H1b_comp["Petitioner State"] == "TX"].groupby("Industry (NAICS) Code")["NewEmpAppr_int"].sum().nlargest(10))

Industry (NAICS) Code
54 - Professional, Scientific, and Technical Services                            44467.0
61 - Educational Services                                                         6529.0
31-33 - Manufacturing                                                             5183.0
51 - Information                                                                  3482.0
62 - Health Care and Social Assistance                                            1560.0
42 - Wholesale Trade                                                              1232.0
52 - Finance and Insurance                                                        1153.0
23 - Construction                                                                  723.0
21 - Mining, Quarrying, and Oil and Gas Extraction                                 695.0
56 - Administrative and Support and Waste Management and Remediation Services      668.0
Name: NewEmpAppr_int, dtype: float64

In [60]:
tx_industry = H1b_comp[H1b_comp["Petitioner State"] == "TX"].groupby("Industry (NAICS) Code")["NewEmpAppr_int"].sum().nlargest(10).sort_values()

fig8 = go.Figure(go.Bar(
    x=tx_industry.values,
    y=tx_industry.index,
    orientation="h",
    marker=dict(
        color=tx_industry.values,
        colorscale="Reds",
        showscale=False
    ),
    hovertemplate="<b>%{y}</b><br>Approvals: %{x:,}<extra></extra>"
))

fig8.update_layout(
    title="Top 10 Industries by H1B Approvals in Texas (2021-2026)",
    xaxis_title="New Employment Approvals",
    yaxis_title="Industry",
    height=500,
    margin={"r": 20, "t": 50, "l": 10, "b": 50}
)

fig8.show()

Now I know the same industry dominates in Texas as well but the second most approval industry is the Educational Services in Texas whereas it is the Manufacturing Industry in California

So for this milestone, I have my charts for the final dashboard coming together. I will have more figures that I will create for the dashboard but the visual is starting to come together.