In [1]:
import pandas as pd
import json

In [2]:
with open("Spotify_Montero_data.json") as j:
    spot = json.load(j)

In [4]:
type(spot)

dict

In [6]:
spot.keys()

dict_keys(['album_type', 'artists', 'available_markets', 'copyrights', 'external_ids', 'external_urls', 'genres', 'href', 'id', 'images', 'label', 'name', 'popularity', 'release_date', 'release_date_precision', 'total_tracks', 'tracks', 'type', 'uri'])

keys is for dictionary {} and index for lists []

In [7]:
spot['genres']

[]

In [8]:
spot['artists']

[{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
  'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
  'id': '7jVv8c5Fj3E9VhNjxT4snq',
  'name': 'Lil Nas X',
  'type': 'artist',
  'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'}]

In [9]:
type(spot['artists'])

list

There is a list stored as the value for key "artists" in the dictionary spot - this is what type function told us

In [10]:
len(spot['artists'])

1

In [11]:
spot['artists'][0]

{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
 'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
 'id': '7jVv8c5Fj3E9VhNjxT4snq',
 'name': 'Lil Nas X',
 'type': 'artist',
 'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'}

In [12]:
spot['artists'][1]

IndexError: list index out of range

In [14]:
type(spot['artists'][0])

dict

In [13]:
spot['artists'][0].keys()

dict_keys(['external_urls', 'href', 'id', 'name', 'type', 'uri'])

In [15]:
spot['artists'][0]['uri']

'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'

In [16]:
type(spot['artists'][0]['uri'])

str

In [18]:
spot['artists'][0]['uri'][8]

'a'

In [19]:
spot['tracks']

{'href': 'https://api.spotify.com/v1/albums/6pOiDiuDQqrmo5DbG0ZubR/tracks?offset=0&limit=50',
 'items': [{'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
     'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
     'id': '7jVv8c5Fj3E9VhNjxT4snq',
     'name': 'Lil Nas X',
     'type': 'artist',
     'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'}],
   'available_markets': ['AD',
    'AE',
    'AG',
    'AL',
    'AM',
    'AO',
    'AR',
    'AT',
    'AU',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BN',
    'BO',
    'BR',
    'BS',
    'BT',
    'BW',
    'BY',
    'BZ',
    'CA',
    'CD',
    'CG',
    'CH',
    'CI',
    'CL',
    'CM',
    'CO',
    'CR',
    'CV',
    'CW',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'ET',
    'FI',
    'FJ',
    'FM',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GH',
    'GM',
    'GN',
    'GQ',
    'GR',
    'GT',
    'GW',
    'GY',
    'HK',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IQ',
    'IS',
    'IT',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KR',
    'KW',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MG',
    'MH',
    'MK',
    'ML',
    'MN',
    'MO',
    'MR',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NE',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PG',
    'PH',
    'PK',
    'PL',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RO',
    'RS',
    'RW',
    'SA',
    'SB',
    'SC',
    'SE',
    'SG',
    'SI',
    'SK',
    'SL',
    'SM',
    'SN',
    'SR',
    'ST',
    'SV',
    'SZ',
    'TD',
    'TG',
    'TH',
    'TJ',
    'TL',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    'VC',
    'VE',
    'VN',
    'VU',
    'WS',
    'XK',
    'ZA',
    'ZM',
    'ZW'],
   'disc_number': 1,
   'duration_ms': 137704,
   'explicit': True,
   'external_urls': {'spotify': 'https://open.spotify.com/track/1SC5rEoYDGUK4NfG82494W'},
   'href': 'https://api.spotify.com/v1/tracks/1SC5rEoYDGUK4NfG82494W',
   'id': '1SC5rEoYDGUK4NfG82494W',
   'is_local': False,
   'name': 'MONTERO (Call Me By Your Name)',
   'preview_url': 'https://p.scdn.co/mp3-preview/a25aff06d2a2f2cf4c5d8d9a7e45ce50789cab50?cid=57cd9c1fb9ad4a53aaab53a9796ba7e9',
   'track_number': 1,
   'type': 'track',
   'uri': 'spotify:track:1SC5rEoYDGUK4NfG82494W'},
  {'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
     'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
     'id': '7jVv8c5Fj3E9VhNjxT4snq',
     'name': 'Lil Nas X',
     'type': 'artist',
     'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'}],
   'available_markets': ['AD',
    'AE',
    'AG',
    'AL',
    'AM',
    'AO',
    'AR',
    'AT',
    'AU',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BN',
    'BO',
    'BR',
    'BS',
    'BT',
    'BW',
    'BY',
    'BZ',
    'CA',
    'CD',
    'CG',
    'CH',
    'CI',
    'CL',
    'CM',
    'CO',
    'CR',
    'CV',
    'CW',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'ET',
    'FI',
    'FJ',
    'FM',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GH',
    'GM',
    'GN',
    'GQ',
    'GR',
    'GT',
    'GW',
    'GY',
    'HK',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IQ',
    'IS',
    'IT',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KR',
    'KW',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MG',
    'MH',
    'MK',
    'ML',
    'MN',
    'MO',
    'MR',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NE',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PG',
    'PH',
    'PK',
    'PL',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RO',
    'RS',
    'RW',
    'SA',
    'SB',
    'SC',
    'SE',
    'SG',
    'SI',
    'SK',
    'SL',
    'SM',
    'SN',
    'SR',
    'ST',
    'SV',
    'SZ',
    'TD',
    'TG',
    'TH',
    'TJ',
    'TL',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    'VC',
    'VE',
    'VN',
    'VU',
    'WS',
    'XK',
    'ZA',
    'ZM',
    'ZW'],
   'disc_number': 1,
   'duration_ms': 221203,
   'explicit': True,
   'external_urls': {'spotify': 'https://open.spotify.com/track/3grVoZ10bm2jUGpo7BxpuF'},
   'href': 'https://api.spotify.com/v1/tracks/3grVoZ10bm2jUGpo7BxpuF',
   'id': '3grVoZ10bm2jUGpo7BxpuF',
   'is_local': False,
   'name': 'DEAD RIGHT NOW',
   'preview_url': 'https://p.scdn.co/mp3-preview/63edfe0701b3d240895575d1e58239ab51bcf9ea?cid=57cd9c1fb9ad4a53aaab53a9796ba7e9',
   'track_number': 2,
   'type': 'track',
   'uri': 'spotify:track:3grVoZ10bm2jUGpo7BxpuF'},
  {'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
     'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
     'id': '7jVv8c5Fj3E9VhNjxT4snq',
     'name': 'Lil Nas X',
     'type': 'artist',
     'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/2LIk90788K0zvyj2JJVwkJ'},
     'href': 'https://api.spotify.com/v1/artists/2LIk90788K0zvyj2JJVwkJ',
     'id': '2LIk90788K0zvyj2JJVwkJ',
     'name': 'Jack Harlow',
     'type': 'artist',
     'uri': 'spotify:artist:2LIk90788K0zvyj2JJVwkJ'}],
   'available_markets': ['AD',
    'AE',
    'AG',
    'AL',
    'AM',
    'AO',
    'AR',
    'AT',
    'AU',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BN',
    'BO',
    'BR',
    'BS',
    'BT',
    'BW',
    'BY',
    'BZ',
    'CA',
    'CD',
    'CG',
    'CH',
    'CI',
    'CL',
    'CM',
    'CO',
    'CR',
    'CV',
    'CW',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'ET',
    'FI',
    'FJ',
    'FM',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GH',
    'GM',
    'GN',
    'GQ',
    'GR',
    'GT',
    'GW',
    'GY',
    'HK',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IQ',
    'IS',
    'IT',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KR',
    'KW',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MG',
    'MH',
    'MK',
    'ML',
    'MN',
    'MO',
    'MR',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NE',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PG',
    'PH',
    'PK',
    'PL',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RO',
    'RS',
    'RW',
    'SA',
    'SB',
    'SC',
    'SE',
    'SG',
    'SI',
    'SK',
    'SL',
    'SM',
    'SN',
    'SR',
    'ST',
    'SV',
    'SZ',
    'TD',
    'TG',
    'TH',
    'TJ',
    'TL',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    'VC',
    'VE',
    'VN',
    'VU',
    'WS',
    'XK',
    'ZA',
    'ZM',
    'ZW'],
   'disc_number': 1,
   'duration_ms': 212352,
   'explicit': True,
   'external_urls': {'spotify': 'https://open.spotify.com/track/5Z9KJZvQzH6PFmb8SNkxuk'},
   'href': 'https://api.spotify.com/v1/tracks/5Z9KJZvQzH6PFmb8SNkxuk',
   'id': '5Z9KJZvQzH6PFmb8SNkxuk',
   'is_local': False,
   'name': 'INDUSTRY BABY (feat. Jack Harlow)',
   'preview_url': 'https://p.scdn.co/mp3-preview/31e16e1bc7aad79a7785b12d6f34421943080b5b?cid=57cd9c1fb9ad4a53aaab53a9796ba7e9',
   'track_number': 3,
   'type': 'track',
   'uri': 'spotify:track:5Z9KJZvQzH6PFmb8SNkxuk'},
  {'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
     'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
     'id': '7jVv8c5Fj3E9VhNjxT4snq',
     'name': 'Lil Nas X',
     'type': 'artist',
     'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'}],
   'available_markets': ['AD',
    'AE',
    'AG',
    'AL',
    'AM',
    'AO',
    'AR',
    'AT',
    'AU',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BN',
    'BO',
    'BR',
    'BS',
    'BT',
    'BW',
    'BY',
    'BZ',
    'CA',
    'CD',
    'CG',
    'CH',
    'CI',
    'CL',
    'CM',
    'CO',
    'CR',
    'CV',
    'CW',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'ET',
    'FI',
    'FJ',
    'FM',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GH',
    'GM',
    'GN',
    'GQ',
    'GR',
    'GT',
    'GW',
    'GY',
    'HK',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IQ',
    'IS',
    'IT',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KR',
    'KW',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MG',
    'MH',
    'MK',
    'ML',
    'MN',
    'MO',
    'MR',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NE',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PG',
    'PH',
    'PK',
    'PL',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RO',
    'RS',
    'RW',
    'SA',
    'SB',
    'SC',
    'SE',
    'SG',
    'SI',
    'SK',
    'SL',
    'SM',
    'SN',
    'SR',
    'ST',
    'SV',
    'SZ',
    'TD',
    'TG',
    'TH',
    'TJ',
    'TL',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    'VC',
    'VE',
    'VN',
    'VU',
    'WS',
    'XK',
    'ZA',
    'ZM',
    'ZW'],
   'disc_number': 1,
   'duration_ms': 143901,
   'explicit': True,
   'external_urls': {'spotify': 'https://open.spotify.com/track/0e8nrvls4Qqv5Rfa2UhqmO'},
   'href': 'https://api.spotify.com/v1/tracks/0e8nrvls4Qqv5Rfa2UhqmO',
   'id': '0e8nrvls4Qqv5Rfa2UhqmO',
   'is_local': False,
   'name': 'THATS WHAT I WANT',
   'preview_url': 'https://p.scdn.co/mp3-preview/d62f4961618e4b4d40d823a11c6a6c1bf3fbd649?cid=57cd9c1fb9ad4a53aaab53a9796ba7e9',
   'track_number': 4,
   'type': 'track',
   'uri': 'spotify:track:0e8nrvls4Qqv5Rfa2UhqmO'},
  {'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
     'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
     'id': '7jVv8c5Fj3E9VhNjxT4snq',
     'name': 'Lil Nas X',
     'type': 'artist',
     'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'}],
   'available_markets': ['AD',
    'AE',
    'AG',
    'AL',
    'AM',
    'AO',
    'AR',
    'AT',
    'AU',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BN',
    'BO',
    'BR',
    'BS',
    'BT',
    'BW',
    'BY',
    'BZ',
    'CA',
    'CD',
    'CG',
    'CH',
    'CI',
    'CL',
    'CM',
    'CO',
    'CR',
    'CV',
    'CW',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'ET',
    'FI',
    'FJ',
    'FM',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GH',
    'GM',
    'GN',
    'GQ',
    'GR',
    'GT',
    'GW',
    'GY',
    'HK',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IQ',
    'IS',
    'IT',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KR',
    'KW',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MG',
    'MH',
    'MK',
    'ML',
    'MN',
    'MO',
    'MR',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NE',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PG',
    'PH',
    'PK',
    'PL',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RO',
    'RS',
    'RW',
    'SA',
    'SB',
    'SC',
    'SE',
    'SG',
    'SI',
    'SK',
    'SL',
    'SM',
    'SN',
    'SR',
    'ST',
    'SV',
    'SZ',
    'TD',
    'TG',
    'TH',
    'TJ',
    'TL',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    'VC',
    'VE',
    'VN',
    'VU',
    'WS',
    'XK',
    'ZA',
    'ZM',
    'ZW'],
   'disc_number': 1,
   'duration_ms': 24005,
   'explicit': False,
   'external_urls': {'spotify': 'https://open.spotify.com/track/1BMu5TWvalAGpi5jlhFEBb'},
   'href': 'https://api.spotify.com/v1/tracks/1BMu5TWvalAGpi5jlhFEBb',
   'id': '1BMu5TWvalAGpi5jlhFEBb',
   'is_local': False,
   'name': 'THE ART OF REALIZATION',
   'preview_url': 'https://p.scdn.co/mp3-preview/48abace5e799d0cd4b0bb4aed6798c2a0e116293?cid=57cd9c1fb9ad4a53aaab53a9796ba7e9',
   'track_number': 5,
   'type': 'track',
   'uri': 'spotify:track:1BMu5TWvalAGpi5jlhFEBb'},
  {'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
     'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
     'id': '7jVv8c5Fj3E9VhNjxT4snq',
     'name': 'Lil Nas X',
     'type': 'artist',
     'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/5cj0lLjcoR7YOSnhnX0Po5'},
     'href': 'https://api.spotify.com/v1/artists/5cj0lLjcoR7YOSnhnX0Po5',
     'id': '5cj0lLjcoR7YOSnhnX0Po5',
     'name': 'Doja Cat',
     'type': 'artist',
     'uri': 'spotify:artist:5cj0lLjcoR7YOSnhnX0Po5'}],
   'available_markets': ['AD',
    'AE',
    'AG',
    'AL',
    'AM',
    'AO',
    'AR',
    'AT',
    'AU',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BN',
    'BO',
    'BR',
    'BS',
    'BT',
    'BW',
    'BY',
    'BZ',
    'CA',
    'CD',
    'CG',
    'CH',
    'CI',
    'CL',
    'CM',
    'CO',
    'CR',
    'CV',
    'CW',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'ET',
    'FI',
    'FJ',
    'FM',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GH',
    'GM',
    'GN',
    'GQ',
    'GR',
    'GT',
    'GW',
    'GY',
    'HK',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IQ',
    'IS',
    'IT',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KR',
    'KW',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MG',
    'MH',
    'MK',
    'ML',
    'MN',
    'MO',
    'MR',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NE',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PG',
    'PH',
    'PK',
    'PL',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RO',
    'RS',
    'RW',
    'SA',
    'SB',
    'SC',
    'SE',
    'SG',
    'SI',
    'SK',
    'SL',
    'SM',
    'SN',
    'SR',
    'ST',
    'SV',
    'SZ',
    'TD',
    'TG',
    'TH',
    'TJ',
    'TL',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    'VC',
    'VE',
    'VN',
    'VU',
    'WS',
    'XK',
    'ZA',
    'ZM',
    'ZW'],
   'disc_number': 1,
   'duration_ms': 174164,
   'explicit': True,
   'external_urls': {'spotify': 'https://open.spotify.com/track/6bpq1jGkVz66Q3LYeoXdjZ'},
   'href': 'https://api.spotify.com/v1/tracks/6bpq1jGkVz66Q3LYeoXdjZ',
   'id': '6bpq1jGkVz66Q3LYeoXdjZ',
   'is_local': False,
   'name': 'SCOOP (feat. Doja Cat)',
   'preview_url': 'https://p.scdn.co/mp3-preview/8c9e2876d66e7b7c89525ffec4a66ee7f730b32f?cid=57cd9c1fb9ad4a53aaab53a9796ba7e9',
   'track_number': 6,
   'type': 'track',
   'uri': 'spotify:track:6bpq1jGkVz66Q3LYeoXdjZ'},
  {'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
     'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
     'id': '7jVv8c5Fj3E9VhNjxT4snq',
     'name': 'Lil Nas X',
     'type': 'artist',
     'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/3PhoLpVuITZKcymswpck5b'},
     'href': 'https://api.spotify.com/v1/artists/3PhoLpVuITZKcymswpck5b',
     'id': '3PhoLpVuITZKcymswpck5b',
     'name': 'Elton John',
     'type': 'artist',
     'uri': 'spotify:artist:3PhoLpVuITZKcymswpck5b'}],
   'available_markets': ['AD',
    'AE',
    'AG',
    'AL',
    'AM',
    'AO',
    'AR',
    'AT',
    'AU',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BN',
    'BO',
    'BR',
    'BS',
    'BT',
    'BW',
    'BY',
    'BZ',
    'CA',
    'CD',
    'CG',
    'CH',
    'CI',
    'CL',
    'CM',
    'CO',
    'CR',
    'CV',
    'CW',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'ET',
    'FI',
    'FJ',
    'FM',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GH',
    'GM',
    'GN',
    'GQ',
    'GR',
    'GT',
    'GW',
    'GY',
    'HK',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IQ',
    'IS',
    'IT',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KR',
    'KW',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MG',
    'MH',
    'MK',
    'ML',
    'MN',
    'MO',
    'MR',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NE',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PG',
    'PH',
    'PK',
    'PL',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RO',
    'RS',
    'RW',
    'SA',
    'SB',
    'SC',
    'SE',
    'SG',
    'SI',
    'SK',
    'SL',
    'SM',
    'SN',
    'SR',
    'ST',
    'SV',
    'SZ',
    'TD',
    'TG',
    'TH',
    'TJ',
    'TL',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    'VC',
    'VE',
    'VN',
    'VU',
    'WS',
    'XK',
    'ZA',
    'ZM',
    'ZW'],
   'disc_number': 1,
   'duration_ms': 161666,
   'explicit': True,
   'external_urls': {'spotify': 'https://open.spotify.com/track/3JR2RztQcOjUQGQSybxDIO'},
   'href': 'https://api.spotify.com/v1/tracks/3JR2RztQcOjUQGQSybxDIO',
   'id': '3JR2RztQcOjUQGQSybxDIO',
   'is_local': False,
   'name': 'ONE OF ME (feat. Elton John)',

In [20]:
type(spot['tracks'])

dict

In [21]:
spot['tracks'].keys()

dict_keys(['href', 'items', 'limit', 'next', 'offset', 'previous', 'total'])

In [22]:
spot['tracks']['items']

[{'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
    'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
    'id': '7jVv8c5Fj3E9VhNjxT4snq',
    'name': 'Lil Nas X',
    'type': 'artist',
    'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'}],
  'available_markets': ['AD',
   'AE',
   'AG',
   'AL',
   'AM',
   'AO',
   'AR',
   'AT',
   'AU',
   'AZ',
   'BA',
   'BB',
   'BD',
   'BE',
   'BF',
   'BG',
   'BH',
   'BI',
   'BJ',
   'BN',
   'BO',
   'BR',
   'BS',
   'BT',
   'BW',
   'BY',
   'BZ',
   'CA',
   'CD',
   'CG',
   'CH',
   'CI',
   'CL',
   'CM',
   'CO',
   'CR',
   'CV',
   'CW',
   'CY',
   'CZ',
   'DE',
   'DJ',
   'DK',
   'DM',
   'DO',
   'DZ',
   'EC',
   'EE',
   'EG',
   'ES',
   'ET',
   'FI',
   'FJ',
   'FM',
   'FR',
   'GA',
   'GB',
   'GD',
   'GE',
   'GH',
   'GM',
   'GN',
   'GQ',
   'GR',
   'GT',
   'GW',
   'GY',
   'HK',
   'HN',
   'HR',
   'HT',
   'HU',
   'ID',
   'IE',
   'IL',
   'IN',
   'IQ',
   'IS',
   'IT',
   'JM',
   'JO',
   'JP',
   'KE',
   'KG',
   'KH',
   'KI',
   'KM',
   'KN',
   'KR',
   'KW',
   'KZ',
   'LA',
   'LB',
   'LC',
   'LI',
   'LK',
   'LR',
   'LS',
   'LT',
   'LU',
   'LV',
   'LY',
   'MA',
   'MC',
   'MD',
   'ME',
   'MG',
   'MH',
   'MK',
   'ML',
   'MN',
   'MO',
   'MR',
   'MT',
   'MU',
   'MV',
   'MW',
   'MX',
   'MY',
   'MZ',
   'NA',
   'NE',
   'NG',
   'NI',
   'NL',
   'NO',
   'NP',
   'NR',
   'NZ',
   'OM',
   'PA',
   'PE',
   'PG',
   'PH',
   'PK',
   'PL',
   'PS',
   'PT',
   'PW',
   'PY',
   'QA',
   'RO',
   'RS',
   'RW',
   'SA',
   'SB',
   'SC',
   'SE',
   'SG',
   'SI',
   'SK',
   'SL',
   'SM',
   'SN',
   'SR',
   'ST',
   'SV',
   'SZ',
   'TD',
   'TG',
   'TH',
   'TJ',
   'TL',
   'TN',
   'TO',
   'TR',
   'TT',
   'TV',
   'TW',
   'TZ',
   'UA',
   'UG',
   'US',
   'UY',
   'UZ',
   'VC',
   'VE',
   'VN',
   'VU',
   'WS',
   'XK',
   'ZA',
   'ZM',
   'ZW'],
  'disc_number': 1,
  'duration_ms': 137704,
  'explicit': True,
  'external_urls': {'spotify': 'https://open.spotify.com/track/1SC5rEoYDGUK4NfG82494W'},
  'href': 'https://api.spotify.com/v1/tracks/1SC5rEoYDGUK4NfG82494W',
  'id': '1SC5rEoYDGUK4NfG82494W',
  'is_local': False,
  'name': 'MONTERO (Call Me By Your Name)',
  'preview_url': 'https://p.scdn.co/mp3-preview/a25aff06d2a2f2cf4c5d8d9a7e45ce50789cab50?cid=57cd9c1fb9ad4a53aaab53a9796ba7e9',
  'track_number': 1,
  'type': 'track',
  'uri': 'spotify:track:1SC5rEoYDGUK4NfG82494W'},
 {'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
    'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
    'id': '7jVv8c5Fj3E9VhNjxT4snq',
    'name': 'Lil Nas X',
    'type': 'artist',
    'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'}],
  'available_markets': ['AD',
   'AE',
   'AG',
   'AL',
   'AM',
   'AO',
   'AR',
   'AT',
   'AU',
   'AZ',
   'BA',
   'BB',
   'BD',
   'BE',
   'BF',
   'BG',
   'BH',
   'BI',
   'BJ',
   'BN',
   'BO',
   'BR',
   'BS',
   'BT',
   'BW',
   'BY',
   'BZ',
   'CA',
   'CD',
   'CG',
   'CH',
   'CI',
   'CL',
   'CM',
   'CO',
   'CR',
   'CV',
   'CW',
   'CY',
   'CZ',
   'DE',
   'DJ',
   'DK',
   'DM',
   'DO',
   'DZ',
   'EC',
   'EE',
   'EG',
   'ES',
   'ET',
   'FI',
   'FJ',
   'FM',
   'FR',
   'GA',
   'GB',
   'GD',
   'GE',
   'GH',
   'GM',
   'GN',
   'GQ',
   'GR',
   'GT',
   'GW',
   'GY',
   'HK',
   'HN',
   'HR',
   'HT',
   'HU',
   'ID',
   'IE',
   'IL',
   'IN',
   'IQ',
   'IS',
   'IT',
   'JM',
   'JO',
   'JP',
   'KE',
   'KG',
   'KH',
   'KI',
   'KM',
   'KN',
   'KR',
   'KW',
   'KZ',
   'LA',
   'LB',
   'LC',
   'LI',
   'LK',
   'LR',
   'LS',
   'LT',
   'LU',
   'LV',
   'LY',
   'MA',
   'MC',
   'MD',
   'ME',
   'MG',
   'MH',
   'MK',
   'ML',
   'MN',
   'MO',
   'MR',
   'MT',
   'MU',
   'MV',
   'MW',
   'MX',
   'MY',
   'MZ',
   'NA',
   'NE',
   'NG',
   'NI',
   'NL',
   'NO',
   'NP',
   'NR',
   'NZ',
   'OM',
   'PA',
   'PE',
   'PG',
   'PH',
   'PK',
   'PL',
   'PS',
   'PT',
   'PW',
   'PY',
   'QA',
   'RO',
   'RS',
   'RW',
   'SA',
   'SB',
   'SC',
   'SE',
   'SG',
   'SI',
   'SK',
   'SL',
   'SM',
   'SN',
   'SR',
   'ST',
   'SV',
   'SZ',
   'TD',
   'TG',
   'TH',
   'TJ',
   'TL',
   'TN',
   'TO',
   'TR',
   'TT',
   'TV',
   'TW',
   'TZ',
   'UA',
   'UG',
   'US',
   'UY',
   'UZ',
   'VC',
   'VE',
   'VN',
   'VU',
   'WS',
   'XK',
   'ZA',
   'ZM',
   'ZW'],
  'disc_number': 1,
  'duration_ms': 221203,
  'explicit': True,
  'external_urls': {'spotify': 'https://open.spotify.com/track/3grVoZ10bm2jUGpo7BxpuF'},
  'href': 'https://api.spotify.com/v1/tracks/3grVoZ10bm2jUGpo7BxpuF',
  'id': '3grVoZ10bm2jUGpo7BxpuF',
  'is_local': False,
  'name': 'DEAD RIGHT NOW',
  'preview_url': 'https://p.scdn.co/mp3-preview/63edfe0701b3d240895575d1e58239ab51bcf9ea?cid=57cd9c1fb9ad4a53aaab53a9796ba7e9',
  'track_number': 2,
  'type': 'track',
  'uri': 'spotify:track:3grVoZ10bm2jUGpo7BxpuF'},
 {'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
    'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
    'id': '7jVv8c5Fj3E9VhNjxT4snq',
    'name': 'Lil Nas X',
    'type': 'artist',
    'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'},
   {'external_urls': {'spotify': 'https://open.spotify.com/artist/2LIk90788K0zvyj2JJVwkJ'},
    'href': 'https://api.spotify.com/v1/artists/2LIk90788K0zvyj2JJVwkJ',
    'id': '2LIk90788K0zvyj2JJVwkJ',
    'name': 'Jack Harlow',
    'type': 'artist',
    'uri': 'spotify:artist:2LIk90788K0zvyj2JJVwkJ'}],
  'available_markets': ['AD',
   'AE',
   'AG',
   'AL',
   'AM',
   'AO',
   'AR',
   'AT',
   'AU',
   'AZ',
   'BA',
   'BB',
   'BD',
   'BE',
   'BF',
   'BG',
   'BH',
   'BI',
   'BJ',
   'BN',
   'BO',
   'BR',
   'BS',
   'BT',
   'BW',
   'BY',
   'BZ',
   'CA',
   'CD',
   'CG',
   'CH',
   'CI',
   'CL',
   'CM',
   'CO',
   'CR',
   'CV',
   'CW',
   'CY',
   'CZ',
   'DE',
   'DJ',
   'DK',
   'DM',
   'DO',
   'DZ',
   'EC',
   'EE',
   'EG',
   'ES',
   'ET',
   'FI',
   'FJ',
   'FM',
   'FR',
   'GA',
   'GB',
   'GD',
   'GE',
   'GH',
   'GM',
   'GN',
   'GQ',
   'GR',
   'GT',
   'GW',
   'GY',
   'HK',
   'HN',
   'HR',
   'HT',
   'HU',
   'ID',
   'IE',
   'IL',
   'IN',
   'IQ',
   'IS',
   'IT',
   'JM',
   'JO',
   'JP',
   'KE',
   'KG',
   'KH',
   'KI',
   'KM',
   'KN',
   'KR',
   'KW',
   'KZ',
   'LA',
   'LB',
   'LC',
   'LI',
   'LK',
   'LR',
   'LS',
   'LT',
   'LU',
   'LV',
   'LY',
   'MA',
   'MC',
   'MD',
   'ME',
   'MG',
   'MH',
   'MK',
   'ML',
   'MN',
   'MO',
   'MR',
   'MT',
   'MU',
   'MV',
   'MW',
   'MX',
   'MY',
   'MZ',
   'NA',
   'NE',
   'NG',
   'NI',
   'NL',
   'NO',
   'NP',
   'NR',
   'NZ',
   'OM',
   'PA',
   'PE',
   'PG',
   'PH',
   'PK',
   'PL',
   'PS',
   'PT',
   'PW',
   'PY',
   'QA',
   'RO',
   'RS',
   'RW',
   'SA',
   'SB',
   'SC',
   'SE',
   'SG',
   'SI',
   'SK',
   'SL',
   'SM',
   'SN',
   'SR',
   'ST',
   'SV',
   'SZ',
   'TD',
   'TG',
   'TH',
   'TJ',
   'TL',
   'TN',
   'TO',
   'TR',
   'TT',
   'TV',
   'TW',
   'TZ',
   'UA',
   'UG',
   'US',
   'UY',
   'UZ',
   'VC',
   'VE',
   'VN',
   'VU',
   'WS',
   'XK',
   'ZA',
   'ZM',
   'ZW'],
  'disc_number': 1,
  'duration_ms': 212352,
  'explicit': True,
  'external_urls': {'spotify': 'https://open.spotify.com/track/5Z9KJZvQzH6PFmb8SNkxuk'},
  'href': 'https://api.spotify.com/v1/tracks/5Z9KJZvQzH6PFmb8SNkxuk',
  'id': '5Z9KJZvQzH6PFmb8SNkxuk',
  'is_local': False,
  'name': 'INDUSTRY BABY (feat. Jack Harlow)',
  'preview_url': 'https://p.scdn.co/mp3-preview/31e16e1bc7aad79a7785b12d6f34421943080b5b?cid=57cd9c1fb9ad4a53aaab53a9796ba7e9',
  'track_number': 3,
  'type': 'track',
  'uri': 'spotify:track:5Z9KJZvQzH6PFmb8SNkxuk'},
 {'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
    'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
    'id': '7jVv8c5Fj3E9VhNjxT4snq',
    'name': 'Lil Nas X',
    'type': 'artist',
    'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'}],
  'available_markets': ['AD',
   'AE',
   'AG',
   'AL',
   'AM',
   'AO',
   'AR',
   'AT',
   'AU',
   'AZ',
   'BA',
   'BB',
   'BD',
   'BE',
   'BF',
   'BG',
   'BH',
   'BI',
   'BJ',
   'BN',
   'BO',
   'BR',
   'BS',
   'BT',
   'BW',
   'BY',
   'BZ',
   'CA',
   'CD',
   'CG',
   'CH',
   'CI',
   'CL',
   'CM',
   'CO',
   'CR',
   'CV',
   'CW',
   'CY',
   'CZ',
   'DE',
   'DJ',
   'DK',
   'DM',
   'DO',
   'DZ',
   'EC',
   'EE',
   'EG',
   'ES',
   'ET',
   'FI',
   'FJ',
   'FM',
   'FR',
   'GA',
   'GB',
   'GD',
   'GE',
   'GH',
   'GM',
   'GN',
   'GQ',
   'GR',
   'GT',
   'GW',
   'GY',
   'HK',
   'HN',
   'HR',
   'HT',
   'HU',
   'ID',
   'IE',
   'IL',
   'IN',
   'IQ',
   'IS',
   'IT',
   'JM',
   'JO',
   'JP',
   'KE',
   'KG',
   'KH',
   'KI',
   'KM',
   'KN',
   'KR',
   'KW',
   'KZ',
   'LA',
   'LB',
   'LC',
   'LI',
   'LK',
   'LR',
   'LS',
   'LT',
   'LU',
   'LV',
   'LY',
   'MA',
   'MC',
   'MD',
   'ME',
   'MG',
   'MH',
   'MK',
   'ML',
   'MN',
   'MO',
   'MR',
   'MT',
   'MU',
   'MV',
   'MW',
   'MX',
   'MY',
   'MZ',
   'NA',
   'NE',
   'NG',
   'NI',
   'NL',
   'NO',
   'NP',
   'NR',
   'NZ',
   'OM',
   'PA',
   'PE',
   'PG',
   'PH',
   'PK',
   'PL',
   'PS',
   'PT',
   'PW',
   'PY',
   'QA',
   'RO',
   'RS',
   'RW',
   'SA',
   'SB',
   'SC',
   'SE',
   'SG',
   'SI',
   'SK',
   'SL',
   'SM',
   'SN',
   'SR',
   'ST',
   'SV',
   'SZ',
   'TD',
   'TG',
   'TH',
   'TJ',
   'TL',
   'TN',
   'TO',
   'TR',
   'TT',
   'TV',
   'TW',
   'TZ',
   'UA',
   'UG',
   'US',
   'UY',
   'UZ',
   'VC',
   'VE',
   'VN',
   'VU',
   'WS',
   'XK',
   'ZA',
   'ZM',
   'ZW'],
  'disc_number': 1,
  'duration_ms': 143901,
  'explicit': True,
  'external_urls': {'spotify': 'https://open.spotify.com/track/0e8nrvls4Qqv5Rfa2UhqmO'},
  'href': 'https://api.spotify.com/v1/tracks/0e8nrvls4Qqv5Rfa2UhqmO',
  'id': '0e8nrvls4Qqv5Rfa2UhqmO',
  'is_local': False,
  'name': 'THATS WHAT I WANT',
  'preview_url': 'https://p.scdn.co/mp3-preview/d62f4961618e4b4d40d823a11c6a6c1bf3fbd649?cid=57cd9c1fb9ad4a53aaab53a9796ba7e9',
  'track_number': 4,
  'type': 'track',
  'uri': 'spotify:track:0e8nrvls4Qqv5Rfa2UhqmO'},
 {'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
    'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
    'id': '7jVv8c5Fj3E9VhNjxT4snq',
    'name': 'Lil Nas X',
    'type': 'artist',
    'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'}],
  'available_markets': ['AD',
   'AE',
   'AG',
   'AL',
   'AM',
   'AO',
   'AR',
   'AT',
   'AU',
   'AZ',
   'BA',
   'BB',
   'BD',
   'BE',
   'BF',
   'BG',
   'BH',
   'BI',
   'BJ',
   'BN',
   'BO',
   'BR',
   'BS',
   'BT',
   'BW',
   'BY',
   'BZ',
   'CA',
   'CD',
   'CG',
   'CH',
   'CI',
   'CL',
   'CM',
   'CO',
   'CR',
   'CV',
   'CW',
   'CY',
   'CZ',
   'DE',
   'DJ',
   'DK',
   'DM',
   'DO',
   'DZ',
   'EC',
   'EE',
   'EG',
   'ES',
   'ET',
   'FI',
   'FJ',
   'FM',
   'FR',
   'GA',
   'GB',
   'GD',
   'GE',
   'GH',
   'GM',
   'GN',
   'GQ',
   'GR',
   'GT',
   'GW',
   'GY',
   'HK',
   'HN',
   'HR',
   'HT',
   'HU',
   'ID',
   'IE',
   'IL',
   'IN',
   'IQ',
   'IS',
   'IT',
   'JM',
   'JO',
   'JP',
   'KE',
   'KG',
   'KH',
   'KI',
   'KM',
   'KN',
   'KR',
   'KW',
   'KZ',
   'LA',
   'LB',
   'LC',
   'LI',
   'LK',
   'LR',
   'LS',
   'LT',
   'LU',
   'LV',
   'LY',
   'MA',
   'MC',
   'MD',
   'ME',
   'MG',
   'MH',
   'MK',
   'ML',
   'MN',
   'MO',
   'MR',
   'MT',
   'MU',
   'MV',
   'MW',
   'MX',
   'MY',
   'MZ',
   'NA',
   'NE',
   'NG',
   'NI',
   'NL',
   'NO',
   'NP',
   'NR',
   'NZ',
   'OM',
   'PA',
   'PE',
   'PG',
   'PH',
   'PK',
   'PL',
   'PS',
   'PT',
   'PW',
   'PY',
   'QA',
   'RO',
   'RS',
   'RW',
   'SA',
   'SB',
   'SC',
   'SE',
   'SG',
   'SI',
   'SK',
   'SL',
   'SM',
   'SN',
   'SR',
   'ST',
   'SV',
   'SZ',
   'TD',
   'TG',
   'TH',
   'TJ',
   'TL',
   'TN',
   'TO',
   'TR',
   'TT',
   'TV',
   'TW',
   'TZ',
   'UA',
   'UG',
   'US',
   'UY',
   'UZ',
   'VC',
   'VE',
   'VN',
   'VU',
   'WS',
   'XK',
   'ZA',
   'ZM',
   'ZW'],
  'disc_number': 1,
  'duration_ms': 24005,
  'explicit': False,
  'external_urls': {'spotify': 'https://open.spotify.com/track/1BMu5TWvalAGpi5jlhFEBb'},
  'href': 'https://api.spotify.com/v1/tracks/1BMu5TWvalAGpi5jlhFEBb',
  'id': '1BMu5TWvalAGpi5jlhFEBb',
  'is_local': False,
  'name': 'THE ART OF REALIZATION',
  'preview_url': 'https://p.scdn.co/mp3-preview/48abace5e799d0cd4b0bb4aed6798c2a0e116293?cid=57cd9c1fb9ad4a53aaab53a9796ba7e9',
  'track_number': 5,
  'type': 'track',
  'uri': 'spotify:track:1BMu5TWvalAGpi5jlhFEBb'},
 {'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
    'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
    'id': '7jVv8c5Fj3E9VhNjxT4snq',
    'name': 'Lil Nas X',
    'type': 'artist',
    'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'},
   {'external_urls': {'spotify': 'https://open.spotify.com/artist/5cj0lLjcoR7YOSnhnX0Po5'},
    'href': 'https://api.spotify.com/v1/artists/5cj0lLjcoR7YOSnhnX0Po5',
    'id': '5cj0lLjcoR7YOSnhnX0Po5',
    'name': 'Doja Cat',
    'type': 'artist',
    'uri': 'spotify:artist:5cj0lLjcoR7YOSnhnX0Po5'}],
  'available_markets': ['AD',
   'AE',
   'AG',
   'AL',
   'AM',
   'AO',
   'AR',
   'AT',
   'AU',
   'AZ',
   'BA',
   'BB',
   'BD',
   'BE',
   'BF',
   'BG',
   'BH',
   'BI',
   'BJ',
   'BN',
   'BO',
   'BR',
   'BS',
   'BT',
   'BW',
   'BY',
   'BZ',
   'CA',
   'CD',
   'CG',
   'CH',
   'CI',
   'CL',
   'CM',
   'CO',
   'CR',
   'CV',
   'CW',
   'CY',
   'CZ',
   'DE',
   'DJ',
   'DK',
   'DM',
   'DO',
   'DZ',
   'EC',
   'EE',
   'EG',
   'ES',
   'ET',
   'FI',
   'FJ',
   'FM',
   'FR',
   'GA',
   'GB',
   'GD',
   'GE',
   'GH',
   'GM',
   'GN',
   'GQ',
   'GR',
   'GT',
   'GW',
   'GY',
   'HK',
   'HN',
   'HR',
   'HT',
   'HU',
   'ID',
   'IE',
   'IL',
   'IN',
   'IQ',
   'IS',
   'IT',
   'JM',
   'JO',
   'JP',
   'KE',
   'KG',
   'KH',
   'KI',
   'KM',
   'KN',
   'KR',
   'KW',
   'KZ',
   'LA',
   'LB',
   'LC',
   'LI',
   'LK',
   'LR',
   'LS',
   'LT',
   'LU',
   'LV',
   'LY',
   'MA',
   'MC',
   'MD',
   'ME',
   'MG',
   'MH',
   'MK',
   'ML',
   'MN',
   'MO',
   'MR',
   'MT',
   'MU',
   'MV',
   'MW',
   'MX',
   'MY',
   'MZ',
   'NA',
   'NE',
   'NG',
   'NI',
   'NL',
   'NO',
   'NP',
   'NR',
   'NZ',
   'OM',
   'PA',
   'PE',
   'PG',
   'PH',
   'PK',
   'PL',
   'PS',
   'PT',
   'PW',
   'PY',
   'QA',
   'RO',
   'RS',
   'RW',
   'SA',
   'SB',
   'SC',
   'SE',
   'SG',
   'SI',
   'SK',
   'SL',
   'SM',
   'SN',
   'SR',
   'ST',
   'SV',
   'SZ',
   'TD',
   'TG',
   'TH',
   'TJ',
   'TL',
   'TN',
   'TO',
   'TR',
   'TT',
   'TV',
   'TW',
   'TZ',
   'UA',
   'UG',
   'US',
   'UY',
   'UZ',
   'VC',
   'VE',
   'VN',
   'VU',
   'WS',
   'XK',
   'ZA',
   'ZM',
   'ZW'],
  'disc_number': 1,
  'duration_ms': 174164,
  'explicit': True,
  'external_urls': {'spotify': 'https://open.spotify.com/track/6bpq1jGkVz66Q3LYeoXdjZ'},
  'href': 'https://api.spotify.com/v1/tracks/6bpq1jGkVz66Q3LYeoXdjZ',
  'id': '6bpq1jGkVz66Q3LYeoXdjZ',
  'is_local': False,
  'name': 'SCOOP (feat. Doja Cat)',
  'preview_url': 'https://p.scdn.co/mp3-preview/8c9e2876d66e7b7c89525ffec4a66ee7f730b32f?cid=57cd9c1fb9ad4a53aaab53a9796ba7e9',
  'track_number': 6,
  'type': 'track',
  'uri': 'spotify:track:6bpq1jGkVz66Q3LYeoXdjZ'},
 {'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
    'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
    'id': '7jVv8c5Fj3E9VhNjxT4snq',
    'name': 'Lil Nas X',
    'type': 'artist',
    'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'},
   {'external_urls': {'spotify': 'https://open.spotify.com/artist/3PhoLpVuITZKcymswpck5b'},
    'href': 'https://api.spotify.com/v1/artists/3PhoLpVuITZKcymswpck5b',
    'id': '3PhoLpVuITZKcymswpck5b',
    'name': 'Elton John',
    'type': 'artist',
    'uri': 'spotify:artist:3PhoLpVuITZKcymswpck5b'}],
  'available_markets': ['AD',
   'AE',
   'AG',
   'AL',
   'AM',
   'AO',
   'AR',
   'AT',
   'AU',
   'AZ',
   'BA',
   'BB',
   'BD',
   'BE',
   'BF',
   'BG',
   'BH',
   'BI',
   'BJ',
   'BN',
   'BO',
   'BR',
   'BS',
   'BT',
   'BW',
   'BY',
   'BZ',
   'CA',
   'CD',
   'CG',
   'CH',
   'CI',
   'CL',
   'CM',
   'CO',
   'CR',
   'CV',
   'CW',
   'CY',
   'CZ',
   'DE',
   'DJ',
   'DK',
   'DM',
   'DO',
   'DZ',
   'EC',
   'EE',
   'EG',
   'ES',
   'ET',
   'FI',
   'FJ',
   'FM',
   'FR',
   'GA',
   'GB',
   'GD',
   'GE',
   'GH',
   'GM',
   'GN',
   'GQ',
   'GR',
   'GT',
   'GW',
   'GY',
   'HK',
   'HN',
   'HR',
   'HT',
   'HU',
   'ID',
   'IE',
   'IL',
   'IN',
   'IQ',
   'IS',
   'IT',
   'JM',
   'JO',
   'JP',
   'KE',
   'KG',
   'KH',
   'KI',
   'KM',
   'KN',
   'KR',
   'KW',
   'KZ',
   'LA',
   'LB',
   'LC',
   'LI',
   'LK',
   'LR',
   'LS',
   'LT',
   'LU',
   'LV',
   'LY',
   'MA',
   'MC',
   'MD',
   'ME',
   'MG',
   'MH',
   'MK',
   'ML',
   'MN',
   'MO',
   'MR',
   'MT',
   'MU',
   'MV',
   'MW',
   'MX',
   'MY',
   'MZ',
   'NA',
   'NE',
   'NG',
   'NI',
   'NL',
   'NO',
   'NP',
   'NR',
   'NZ',
   'OM',
   'PA',
   'PE',
   'PG',
   'PH',
   'PK',
   'PL',
   'PS',
   'PT',
   'PW',
   'PY',
   'QA',
   'RO',
   'RS',
   'RW',
   'SA',
   'SB',
   'SC',
   'SE',
   'SG',
   'SI',
   'SK',
   'SL',
   'SM',
   'SN',
   'SR',
   'ST',
   'SV',
   'SZ',
   'TD',
   'TG',
   'TH',
   'TJ',
   'TL',
   'TN',
   'TO',
   'TR',
   'TT',
   'TV',
   'TW',
   'TZ',
   'UA',
   'UG',
   'US',
   'UY',
   'UZ',
   'VC',
   'VE',
   'VN',
   'VU',
   'WS',
   'XK',
   'ZA',
   'ZM',
   'ZW'],
  'disc_number': 1,
  'duration_ms': 161666,
  'explicit': True,
  'external_urls': {'spotify': 'https://open.spotify.com/track/3JR2RztQcOjUQGQSybxDIO'},
  'href': 'https://api.spotify.com/v1/tracks/3JR2RztQcOjUQGQSybxDIO',
  'id': '3JR2RztQcOjUQGQSybxDIO',
  'is_local': False,
  'name': 'ONE OF ME (feat. Elton John)',
  'preview_url': 'https://p.scdn.co/mp3-preview/b9f6687836ff21429157610e99449760a6428f8a?cid=57cd9c1fb9ad4a53aaab53a9796ba7e9',
  'track_number': 7,
  'type': 'track',
  'uri': 'spotify:track:3JR2RztQcOjUQGQSybxDIO'},
 {'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
    'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
    'id': '7jVv8c5Fj3E9VhNjxT4snq',
    'name': 'Lil Nas X',
    'type': 'artist',
    'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'}],
  'available_markets': ['AD',
   'AE',
   'AG',
   'AL',
   'AM',
   'AO',
   'AR',
   'AT',
   'AU',
   'AZ',
   'BA',
   'BB',
   'BD',
   'BE',
   'BF',
   'BG',
   'BH',
   'BI',
   'BJ',
   'BN',
   'BO',
   'BR',
   'BS',
   'BT',
   'BW',
   'BY',
   'BZ',
   'CA',
   'CD',
   'CG',
   'CH',
   'CI',
   'CL',
   'CM',
   'CO',
   'CR',
   'CV',
   'CW',
   'CY',
   'CZ',
   'DE',
   'DJ',
   'DK',
   'DM',
   'DO',
   'DZ',
   'EC',
   'EE',
   'EG',
   'ES',
   'ET',
   'FI',
   'FJ',
   'FM',
   'FR',
   'GA',
   'GB',
   'GD',
   'GE',
   'GH',
   'GM',
   'GN',
   'GQ',
   'GR',
   'GT',
   'GW',
   'GY',
   'HK',
   'HN',
   'HR',
   'HT',
   'HU',
   'ID',
   'IE',
   'IL',
   'IN',
   'IQ',
   'IS',
   'IT',
   'JM',
   'JO',
   'JP',
   'KE',
   'KG',
   'KH',
   'KI',
   'KM',
   'KN',
   'KR',
   'KW',
   'KZ',
   'LA',
   'LB',
   'LC',
   'LI',
   'LK',
   'LR',
   'LS',
   'LT',
   'LU',
   'LV',
   'LY',
   'MA',
   'MC',
   'MD',
   'ME',
   'MG',
   'MH',
   'MK',
   'ML',
   'MN',
   'MO',
   'MR',
   'MT',
   'MU',
   'MV',
   'MW',
   'MX',
   'MY',
   'MZ',

In [23]:
type(spot['tracks']['items'])

list

In [25]:
len(spot['tracks']['items'])

15

In [26]:
spot['tracks']['items'][7]

{'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
   'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
   'id': '7jVv8c5Fj3E9VhNjxT4snq',
   'name': 'Lil Nas X',
   'type': 'artist',
   'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'}],
 'available_markets': ['AD',
  'AE',
  'AG',
  'AL',
  'AM',
  'AO',
  'AR',
  'AT',
  'AU',
  'AZ',
  'BA',
  'BB',
  'BD',
  'BE',
  'BF',
  'BG',
  'BH',
  'BI',
  'BJ',
  'BN',
  'BO',
  'BR',
  'BS',
  'BT',
  'BW',
  'BY',
  'BZ',
  'CA',
  'CD',
  'CG',
  'CH',
  'CI',
  'CL',
  'CM',
  'CO',
  'CR',
  'CV',
  'CW',
  'CY',
  'CZ',
  'DE',
  'DJ',
  'DK',
  'DM',
  'DO',
  'DZ',
  'EC',
  'EE',
  'EG',
  'ES',
  'ET',
  'FI',
  'FJ',
  'FM',
  'FR',
  'GA',
  'GB',
  'GD',
  'GE',
  'GH',
  'GM',
  'GN',
  'GQ',
  'GR',
  'GT',
  'GW',
  'GY',
  'HK',
  'HN',
  'HR',
  'HT',
  'HU',
  'ID',
  'IE',
  'IL',
  'IN',
  'IQ',
  'IS',
  'IT',
  'JM',
  'JO',
  'JP',
  'KE',
  'KG',
  'KH',
  'KI',
  'KM',
  'KN',
  'KR',
  'KW',
  'KZ',
  'LA',
  'LB',
  'LC',
  'LI',
  'LK',
  'LR',
  'LS',
  'LT',
  'LU',
  'LV',
  'LY',
  'MA',
  'MC',
  'MD',
  'ME',
  'MG',
  'MH',
  'MK',
  'ML',
  'MN',
  'MO',
  'MR',
  'MT',
  'MU',
  'MV',
  'MW',
  'MX',
  'MY',
  'MZ',
  'NA',
  'NE',
  'NG',
  'NI',
  'NL',
  'NO',
  'NP',
  'NR',
  'NZ',
  'OM',
  'PA',
  'PE',
  'PG',
  'PH',
  'PK',
  'PL',
  'PS',
  'PT',
  'PW',
  'PY',
  'QA',
  'RO',
  'RS',
  'RW',
  'SA',
  'SB',
  'SC',
  'SE',
  'SG',
  'SI',
  'SK',
  'SL',
  'SM',
  'SN',
  'SR',
  'ST',
  'SV',
  'SZ',
  'TD',
  'TG',
  'TH',
  'TJ',
  'TL',
  'TN',
  'TO',
  'TR',
  'TT',
  'TV',
  'TW',
  'TZ',
  'UA',
  'UG',
  'US',
  'UY',
  'UZ',
  'VC',
  'VE',
  'VN',
  'VU',
  'WS',
  'XK',
  'ZA',
  'ZM',
  'ZW'],
 'disc_number': 1,
 'duration_ms': 170322,
 'explicit': False,
 'external_urls': {'spotify': 'https://open.spotify.com/track/6th8IdY4lYeM0QlSQJhhkp'},
 'href': 'https://api.spotify.com/v1/tracks/6th8IdY4lYeM0QlSQJhhkp',
 'id': '6th8IdY4lYeM0QlSQJhhkp',
 'is_local': False,
 'name': 'LOST IN THE CITADEL',
 'preview_url': 'https://p.scdn.co/mp3-preview/a73ff140bd2349d33b355cfa74b51980d0452e50?cid=57cd9c1fb9ad4a53aaab53a9796ba7e9',
 'track_number': 8,
 'type': 'track',
 'uri': 'spotify:track:6th8IdY4lYeM0QlSQJhhkp'}

In [27]:
spot['tracks']['items'][7].keys()

dict_keys(['artists', 'available_markets', 'disc_number', 'duration_ms', 'explicit', 'external_urls', 'href', 'id', 'is_local', 'name', 'preview_url', 'track_number', 'type', 'uri'])

In [30]:
type(spot['tracks']['items'][7]['available_markets'])

list

In [28]:
montero_tracks = pd.DataFrame(spot['tracks']['items'])
montero_tracks.head()

,artists,available_markets,disc_number,duration_ms,explicit,external_urls,href,id,is_local,name,preview_url,track_number,type,uri
0,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,137704,True,{'spotify': 'https://open.spotify.com/track/1S...,https://api.spotify.com/v1/tracks/1SC5rEoYDGUK...,1SC5rEoYDGUK4NfG82494W,False,MONTERO (Call Me By Your Name),https://p.scdn.co/mp3-preview/a25aff06d2a2f2cf...,1,track,spotify:track:1SC5rEoYDGUK4NfG82494W
1,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,221203,True,{'spotify': 'https://open.spotify.com/track/3g...,https://api.spotify.com/v1/tracks/3grVoZ10bm2j...,3grVoZ10bm2jUGpo7BxpuF,False,DEAD RIGHT NOW,https://p.scdn.co/mp3-preview/63edfe0701b3d240...,2,track,spotify:track:3grVoZ10bm2jUGpo7BxpuF
2,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,212352,True,{'spotify': 'https://open.spotify.com/track/5Z...,https://api.spotify.com/v1/tracks/5Z9KJZvQzH6P...,5Z9KJZvQzH6PFmb8SNkxuk,False,INDUSTRY BABY (feat. Jack Harlow),https://p.scdn.co/mp3-preview/31e16e1bc7aad79a...,3,track,spotify:track:5Z9KJZvQzH6PFmb8SNkxuk
3,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,143901,True,{'spotify': 'https://open.spotify.com/track/0e...,https://api.spotify.com/v1/tracks/0e8nrvls4Qqv...,0e8nrvls4Qqv5Rfa2UhqmO,False,THATS WHAT I WANT,https://p.scdn.co/mp3-preview/d62f4961618e4b4d...,4,track,spotify:track:0e8nrvls4Qqv5Rfa2UhqmO
4,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,24005,False,{'spotify': 'https://open.spotify.com/track/1B...,https://api.spotify.com/v1/tracks/1BMu5TWvalAG...,1BMu5TWvalAGpi5jlhFEBb,False,THE ART OF REALIZATION,https://p.scdn.co/mp3-preview/48abace5e799d0cd...,5,track,spotify:track:1BMu5TWvalAGpi5jlhFEBb

In [31]:
montero_tracks['available_markets'].iloc[0]

['AD',
 'AE',
 'AG',
 'AL',
 'AM',
 'AO',
 'AR',
 'AT',
 'AU',
 'AZ',
 'BA',
 'BB',
 'BD',
 'BE',
 'BF',
 'BG',
 'BH',
 'BI',
 'BJ',
 'BN',
 'BO',
 'BR',
 'BS',
 'BT',
 'BW',
 'BY',
 'BZ',
 'CA',
 'CD',
 'CG',
 'CH',
 'CI',
 'CL',
 'CM',
 'CO',
 'CR',
 'CV',
 'CW',
 'CY',
 'CZ',
 'DE',
 'DJ',
 'DK',
 'DM',
 'DO',
 'DZ',
 'EC',
 'EE',
 'EG',
 'ES',
 'ET',
 'FI',
 'FJ',
 'FM',
 'FR',
 'GA',
 'GB',
 'GD',
 'GE',
 'GH',
 'GM',
 'GN',
 'GQ',
 'GR',
 'GT',
 'GW',
 'GY',
 'HK',
 'HN',
 'HR',
 'HT',
 'HU',
 'ID',
 'IE',
 'IL',
 'IN',
 'IQ',
 'IS',
 'IT',
 'JM',
 'JO',
 'JP',
 'KE',
 'KG',
 'KH',
 'KI',
 'KM',
 'KN',
 'KR',
 'KW',
 'KZ',
 'LA',
 'LB',
 'LC',
 'LI',
 'LK',
 'LR',
 'LS',
 'LT',
 'LU',
 'LV',
 'LY',
 'MA',
 'MC',
 'MD',
 'ME',
 'MG',
 'MH',
 'MK',
 'ML',
 'MN',
 'MO',
 'MR',
 'MT',
 'MU',
 'MV',
 'MW',
 'MX',
 'MY',
 'MZ',
 'NA',
 'NE',
 'NG',
 'NI',
 'NL',
 'NO',
 'NP',
 'NR',
 'NZ',
 'OM',
 'PA',
 'PE',
 'PG',
 'PH',
 'PK',
 'PL',
 'PS',
 'PT',
 'PW',
 'PY',
 'QA',
 'RO',
 'RS',
 'RW',
 'SA',
 'SB',
 'SC',
 'SE',
 'SG',
 'SI',
 'SK',
 'SL',
 'SM',
 'SN',
 'SR',
 'ST',
 'SV',
 'SZ',
 'TD',
 'TG',
 'TH',
 'TJ',
 'TL',
 'TN',
 'TO',
 'TR',
 'TT',
 'TV',
 'TW',
 'TZ',
 'UA',
 'UG',
 'US',
 'UY',
 'UZ',
 'VC',
 'VE',
 'VN',
 'VU',
 'WS',
 'XK',
 'ZA',
 'ZM',
 'ZW']

We use iloc here because now we are working with a data frame

In [32]:
len(montero_tracks['available_markets'].iloc[0])

184

In [34]:
['US' in montero_tracks['available_markets'].iloc[1]]

[True]

for loop - [ x for x in]  
[len(x) for x in ]  
Using square brackets because of lists  
This is called list comprehension  
It iterates over data, applies a function to each element and returns a list to each output

In [35]:
[len(x) for x in montero_tracks['available_markets']]

[184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184]

In [36]:
['US' in x for x in montero_tracks['available_markets']]

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [38]:
["Available" if "US" in x else "not available" for x in montero_tracks['available_markets']]

['Available',
 'Available',
 'Available',
 'Available',
 'Available',
 'Available',
 'Available',
 'Available',
 'Available',
 'Available',
 'Available',
 'Available',
 'Available',
 'Available',
 'Available']

In [39]:
montero_tracks["US"] = ["Available" if "US" in x else "not available" for x in montero_tracks['available_markets']]
montero_tracks.head()

,artists,available_markets,disc_number,duration_ms,explicit,external_urls,href,id,is_local,name,preview_url,track_number,type,uri,US
0,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,137704,True,{'spotify': 'https://open.spotify.com/track/1S...,https://api.spotify.com/v1/tracks/1SC5rEoYDGUK...,1SC5rEoYDGUK4NfG82494W,False,MONTERO (Call Me By Your Name),https://p.scdn.co/mp3-preview/a25aff06d2a2f2cf...,1,track,spotify:track:1SC5rEoYDGUK4NfG82494W,Available
1,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,221203,True,{'spotify': 'https://open.spotify.com/track/3g...,https://api.spotify.com/v1/tracks/3grVoZ10bm2j...,3grVoZ10bm2jUGpo7BxpuF,False,DEAD RIGHT NOW,https://p.scdn.co/mp3-preview/63edfe0701b3d240...,2,track,spotify:track:3grVoZ10bm2jUGpo7BxpuF,Available
2,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,212352,True,{'spotify': 'https://open.spotify.com/track/5Z...,https://api.spotify.com/v1/tracks/5Z9KJZvQzH6P...,5Z9KJZvQzH6PFmb8SNkxuk,False,INDUSTRY BABY (feat. Jack Harlow),https://p.scdn.co/mp3-preview/31e16e1bc7aad79a...,3,track,spotify:track:5Z9KJZvQzH6PFmb8SNkxuk,Available
3,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,143901,True,{'spotify': 'https://open.spotify.com/track/0e...,https://api.spotify.com/v1/tracks/0e8nrvls4Qqv...,0e8nrvls4Qqv5Rfa2UhqmO,False,THATS WHAT I WANT,https://p.scdn.co/mp3-preview/d62f4961618e4b4d...,4,track,spotify:track:0e8nrvls4Qqv5Rfa2UhqmO,Available
4,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,24005,False,{'spotify': 'https://open.spotify.com/track/1B...,https://api.spotify.com/v1/tracks/1BMu5TWvalAG...,1BMu5TWvalAGpi5jlhFEBb,False,THE ART OF REALIZATION,https://p.scdn.co/mp3-preview/48abace5e799d0cd...,5,track,spotify:track:1BMu5TWvalAGpi5jlhFEBb,Available

In [40]:
montero_tracks['artists'].iloc[0]

[{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
  'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
  'id': '7jVv8c5Fj3E9VhNjxT4snq',
  'name': 'Lil Nas X',
  'type': 'artist',
  'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'}]

In [41]:
montero_tracks['artists'].iloc[0][0]['name']

'Lil Nas X'

In [45]:
[x[0]['name'] for x in montero_tracks['artists']]

['Lil Nas X',
 'Lil Nas X',
 'Lil Nas X',
 'Lil Nas X',
 'Lil Nas X',
 'Lil Nas X',
 'Lil Nas X',
 'Lil Nas X',
 'Lil Nas X',
 'Lil Nas X',
 'Lil Nas X',
 'Lil Nas X',
 'Lil Nas X',
 'Lil Nas X',
 'Lil Nas X']

In [43]:
[len(x) for x in montero_tracks['artists']]

[1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2]

In [46]:
montero_tracks['artists'].iloc[2]

[{'external_urls': {'spotify': 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'},
  'href': 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
  'id': '7jVv8c5Fj3E9VhNjxT4snq',
  'name': 'Lil Nas X',
  'type': 'artist',
  'uri': 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/2LIk90788K0zvyj2JJVwkJ'},
  'href': 'https://api.spotify.com/v1/artists/2LIk90788K0zvyj2JJVwkJ',
  'id': '2LIk90788K0zvyj2JJVwkJ',
  'name': 'Jack Harlow',
  'type': 'artist',
  'uri': 'spotify:artist:2LIk90788K0zvyj2JJVwkJ'}]

In [51]:
[[x['name'] for x in y] for y in montero_tracks['artists']]

[['Lil Nas X'],
 ['Lil Nas X'],
 ['Lil Nas X', 'Jack Harlow'],
 ['Lil Nas X'],
 ['Lil Nas X'],
 ['Lil Nas X', 'Doja Cat'],
 ['Lil Nas X', 'Elton John'],
 ['Lil Nas X'],
 ['Lil Nas X', 'Megan Thee Stallion'],
 ['Lil Nas X'],
 ['Lil Nas X'],
 ['Lil Nas X'],
 ['Lil Nas X'],
 ['Lil Nas X'],
 ['Lil Nas X', 'Miley Cyrus']]

In [52]:
','.join(['a', 'b', 'c', 'd', 'e'])

'a,b,c,d,e'

In [54]:
montero_tracks['artist_names'] = [','.join([x['name'] for x in y]) for y in montero_tracks['artists']]
montero_tracks.head()

,artists,available_markets,disc_number,duration_ms,explicit,external_urls,href,id,is_local,name,preview_url,track_number,type,uri,US,artist_names
0,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,137704,True,{'spotify': 'https://open.spotify.com/track/1S...,https://api.spotify.com/v1/tracks/1SC5rEoYDGUK...,1SC5rEoYDGUK4NfG82494W,False,MONTERO (Call Me By Your Name),https://p.scdn.co/mp3-preview/a25aff06d2a2f2cf...,1,track,spotify:track:1SC5rEoYDGUK4NfG82494W,Available,Lil Nas X
1,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,221203,True,{'spotify': 'https://open.spotify.com/track/3g...,https://api.spotify.com/v1/tracks/3grVoZ10bm2j...,3grVoZ10bm2jUGpo7BxpuF,False,DEAD RIGHT NOW,https://p.scdn.co/mp3-preview/63edfe0701b3d240...,2,track,spotify:track:3grVoZ10bm2jUGpo7BxpuF,Available,Lil Nas X
2,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,212352,True,{'spotify': 'https://open.spotify.com/track/5Z...,https://api.spotify.com/v1/tracks/5Z9KJZvQzH6P...,5Z9KJZvQzH6PFmb8SNkxuk,False,INDUSTRY BABY (feat. Jack Harlow),https://p.scdn.co/mp3-preview/31e16e1bc7aad79a...,3,track,spotify:track:5Z9KJZvQzH6PFmb8SNkxuk,Available,"Lil Nas X,Jack Harlow"
3,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,143901,True,{'spotify': 'https://open.spotify.com/track/0e...,https://api.spotify.com/v1/tracks/0e8nrvls4Qqv...,0e8nrvls4Qqv5Rfa2UhqmO,False,THATS WHAT I WANT,https://p.scdn.co/mp3-preview/d62f4961618e4b4d...,4,track,spotify:track:0e8nrvls4Qqv5Rfa2UhqmO,Available,Lil Nas X
4,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,24005,False,{'spotify': 'https://open.spotify.com/track/1B...,https://api.spotify.com/v1/tracks/1BMu5TWvalAG...,1BMu5TWvalAGpi5jlhFEBb,False,THE ART OF REALIZATION,https://p.scdn.co/mp3-preview/48abace5e799d0cd...,5,track,spotify:track:1BMu5TWvalAGpi5jlhFEBb,Available,Lil Nas X

In [55]:
montero_tracks

,artists,available_markets,disc_number,duration_ms,explicit,external_urls,href,id,is_local,name,preview_url,track_number,type,uri,US,artist_names
0,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,137704,True,{'spotify': 'https://open.spotify.com/track/1S...,https://api.spotify.com/v1/tracks/1SC5rEoYDGUK...,1SC5rEoYDGUK4NfG82494W,False,MONTERO (Call Me By Your Name),https://p.scdn.co/mp3-preview/a25aff06d2a2f2cf...,1,track,spotify:track:1SC5rEoYDGUK4NfG82494W,Available,Lil Nas X
1,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,221203,True,{'spotify': 'https://open.spotify.com/track/3g...,https://api.spotify.com/v1/tracks/3grVoZ10bm2j...,3grVoZ10bm2jUGpo7BxpuF,False,DEAD RIGHT NOW,https://p.scdn.co/mp3-preview/63edfe0701b3d240...,2,track,spotify:track:3grVoZ10bm2jUGpo7BxpuF,Available,Lil Nas X
2,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,212352,True,{'spotify': 'https://open.spotify.com/track/5Z...,https://api.spotify.com/v1/tracks/5Z9KJZvQzH6P...,5Z9KJZvQzH6PFmb8SNkxuk,False,INDUSTRY BABY (feat. Jack Harlow),https://p.scdn.co/mp3-preview/31e16e1bc7aad79a...,3,track,spotify:track:5Z9KJZvQzH6PFmb8SNkxuk,Available,"Lil Nas X,Jack Harlow"
3,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,143901,True,{'spotify': 'https://open.spotify.com/track/0e...,https://api.spotify.com/v1/tracks/0e8nrvls4Qqv...,0e8nrvls4Qqv5Rfa2UhqmO,False,THATS WHAT I WANT,https://p.scdn.co/mp3-preview/d62f4961618e4b4d...,4,track,spotify:track:0e8nrvls4Qqv5Rfa2UhqmO,Available,Lil Nas X
4,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,24005,False,{'spotify': 'https://open.spotify.com/track/1B...,https://api.spotify.com/v1/tracks/1BMu5TWvalAG...,1BMu5TWvalAGpi5jlhFEBb,False,THE ART OF REALIZATION,https://p.scdn.co/mp3-preview/48abace5e799d0cd...,5,track,spotify:track:1BMu5TWvalAGpi5jlhFEBb,Available,Lil Nas X
5,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,174164,True,{'spotify': 'https://open.spotify.com/track/6b...,https://api.spotify.com/v1/tracks/6bpq1jGkVz66...,6bpq1jGkVz66Q3LYeoXdjZ,False,SCOOP (feat. Doja Cat),https://p.scdn.co/mp3-preview/8c9e2876d66e7b7c...,6,track,spotify:track:6bpq1jGkVz66Q3LYeoXdjZ,Available,"Lil Nas X,Doja Cat"
6,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,161666,True,{'spotify': 'https://open.spotify.com/track/3J...,https://api.spotify.com/v1/tracks/3JR2RztQcOjU...,3JR2RztQcOjUQGQSybxDIO,False,ONE OF ME (feat. Elton John),https://p.scdn.co/mp3-preview/b9f6687836ff2142...,7,track,spotify:track:3JR2RztQcOjUQGQSybxDIO,Available,"Lil Nas X,Elton John"
7,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,170322,False,{'spotify': 'https://open.spotify.com/track/6t...,https://api.spotify.com/v1/tracks/6th8IdY4lYeM...,6th8IdY4lYeM0QlSQJhhkp,False,LOST IN THE CITADEL,https://p.scdn.co/mp3-preview/a73ff140bd2349d3...,8,track,spotify:track:6th8IdY4lYeM0QlSQJhhkp,Available,Lil Nas X
8,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,145074,True,{'spotify': 'https://open.spotify.com/track/7z...,https://api.spotify.com/v1/tracks/7zQirOExB0VR...,7zQirOExB0VR8yWUOqYeio,False,DOLLA SIGN SLIME (feat. Megan Thee Stallion),https://p.scdn.co/mp3-preview/e8698733174aa642...,9,track,spotify:track:7zQirOExB0VR8yWUOqYeio,Available,"Lil Nas X,Megan Thee Stallion"
9,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,146005,False,{'spotify': 'https://open.spotify.com/track/5S...,https://api.spotify.com/v1/tracks/5S4PZ7AuYlYi...,5S4PZ7AuYlYiVIVik3wHUf,False,TALES OF DOMINICA,https://p.scdn.co/mp3-preview/6005a443164afd33...,10,track,spotify:track:5S4PZ7AuYlYiVIVik3wHUf,Available,Lil Nas X
10,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,168034,False,{'spotify': 'https://open.spotify.com/track/6b...,https://api.spotify.com/v1/tracks/6btdl1Vl6Ta5...,6btdl1Vl6Ta5lUwUSOFW2H,False,SUN GOES DOWN,https://p.scdn.co/mp3-preview/d5427adc7a7b60d4...,11,track,spotify:track:6btdl1Vl6Ta5lUwUSOFW2H,Available,Lil Nas X
11,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,248407,False,{'spotify': 'https://open.spotify.com/track/3e...,https://api.spotify.com/v1/tracks/3e6ebtUCZ0tZ...,3e6ebtUCZ0tZL1J7wvM8Xi,False,VOID,https://p.scdn.co/mp3-preview/ee8270a8d124610e...,12,track,spotify:track:3e6ebtUCZ0tZL1J7wvM8Xi,Available,Lil Nas X
12,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,130925,True,{'spotify': 'https://open.spotify.com/track/4v...,https://api.spotify.com/v1/tracks/4vsJWPwWPS27...,4vsJWPwWPS27gRM4oLjBNO,False,DONT WANT IT,https://p.scdn.co/mp3-preview/18e416c9bce3f8f6...,13,track,spotify:track:4vsJWPwWPS27gRM4oLjBNO,Available,Lil Nas X
13,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,210681,False,{'spotify': 'https://open.spotify.com/track/6D...,https://api.spotify.com/v1/tracks/6D3t4w54PgLN...,6D3t4w54PgLNGQ48R7th7R,False,LIFE AFTER SALEM,https://p.scdn.co/mp3-preview/3c3d838d99091270...,14,track,spotify:track:6D3t4w54PgLNGQ48R7th7R,Available,Lil Nas X
14,[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, B...",1,183241,False,{'spotify': 'https://open.spotify.com/track/6i...,https://api.spotify.com/v1/tracks/6isTQfKXhNO3...,6isTQfKXhNO3EyJd9mSxx8,False,AM I DREAMING (feat. Miley Cyrus),https://p.scdn.co/mp3-preview/736d012d39c35e32...,15,track,spotify:track:6isTQfKXhNO3EyJd9mSxx8,Available,"Lil Nas X,Miley Cyrus"